# post http://localhost:3003/user
# content-type: application/json

# {
#       "name":"ewerton",
#       "nickname":"ton",
#       "email":"ewerton@gmail.com"
# }


# GET http://localhost:3003/user/:id
# content-type: application/json



